version: '3.8'

services:
  # Base de datos PostgreSQL
  db:
    image: postgres:13
    container_name: inventario_db
    environment:
      POSTGRES_DB: inventario_laboratorio
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # API FastAPI
  api:
    build: ./api
    container_name: inventario_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:password123@db:5432/inventario_laboratorio
    restart: unless-stopped
    volumes:
      - ./api:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Aplicación Web Flask
  webapp:
    build: ./webapp
    container_name: inventario_webapp
    ports:
      - "5000:5000"
    depends_on:
      - api
    environment:
      API_URL: http://api:8000
    restart: unless-stopped
    volumes:
      - ./webapp:/app
    command: python app.py

volumes:
  postgres_data: